name       : clutter-gst-2.0
version    : 2.0.16
release    : 3
source     :
    - http://ftp.acc.umu.se/pub/GNOME/sources/clutter-gst/2.0/clutter-gst-2.0.16.tar.xz : a944f84186937021aba6329c23954f6015d33bf151ba8994e13c59cefd742039
license    : LGPL-2.1+
summary    : Clutter GStreamer API
builddeps  :
    - pkgconfig(clutter-1.0)
    - pkgconfig(cogl-1.0)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gstreamer-base-1.0)
    - pkgconfig(gstreamer-video-1.0)
    - pkgconfig(gstreamer-audio-1.0)
    - pkgconfig(gstreamer-tag-1.0)
description: |
    Clutter GStreamer API
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
